### ISSUE TITLE
`get_files` Segmentation Fault when there is no files on clipboard

### ISSUE THREAD

**Issue by HuakunShen** [ChurchTao/clipboard-rs#11]
### The problem | 问题描述

https://github.com/ChurchTao/clipboard-rs/blob/master/examples/files.rs

`get_files` gives me segmentation fault when there is no file on clipboard

```
let files = ctx.get_files().unwrap_or(vec![]);
```

### Release version | 版本

0.1.3

### Operating system | 操作系统

MacOS 14.4 (Arm)

### Logs | 日志

```
["public.utf8-plain-text", "NSStringPboardType", "org.chromium.source-url"]
has_files=false
[1]    91105 segmentation fault  cargo run --bin read_files
```

**Comment by ChurchTao** [comment]
Problems occur occasionally and disappear after restarting, waiting for debug results
