### ISSUE TITLE
ClipboardContext 能否实现 Clone / Copy ？

### ISSUE THREAD

**Issue by StringKe** [ChurchTao/clipboard-rs#13]
### The feature request | 需求描述

尝试将 ClipboardContext 进行保存到对应的状态对象中（ 比如 tauri 提供 manage 存储 state ）

move occurs because value has type `ClipboardContext`, which does not implement the `Copy` trait Help: consider borrowing here

### Proposed solution | 解决方案

None

**Comment by ChurchTao** [comment]
tauri 中，应该可以保存到状态对象中吧，我刚刚写了个 demo 测试了一下，你可以看一下，不过我会思考能不能实现 copy ，目前无法保证这个对象在所有平台都线程安全。

https://github.com/ChurchTao/clipboard-rs-tauri-demo

**Comment by StringKe** [comment]
我是这样写的 tauri 2 beta，还是无法移动它

https://github.com/stringke-org/qingmu/blob/main/src-tauri/src/commands.rs#L26

**Comment by ChurchTao** [comment]
> 我是这样写的 tauri 2 beta，还是无法移动它
> 
> https://github.com/stringke-org/qingmu/blob/main/src-tauri/src/commands.rs#L26

@StringKe 我知道你的困惑了，你的代码中：
`let clipboard_context = &state.0.lock().unwrap().clipboard_context;`
这样做是试图把 对象从 state 中 move 出来，这是移动所有权的做法，这里 move 出来了，state 就会丢失所有权，这在 rust 中是不允许的，你可以改为，使用 `&` 创建一个不可变引用，在函数 `get_clipboard_text` 中这个不可变引用足以完成所有工作，并且不会额外内存开销，state 也不会因此丢失所有权。

示例代码如下：

```rust
#[tauri::command]
pub fn get_clipboard_text(state: tauri::State<'_, AppState>) -> Result<String> {
    // 无法移动
    let clipboard_context = &state.0.lock().unwrap().clipboard_context;
    match clipboard_context.get_text() {
        Ok(str) => {
            if str.is_empty() {
                Err(Error::from(anyhow::anyhow!("Clipboard text is empty")))
            } else {
                Ok(str)
            }
        }
        Err(_) => Err(Error::from(anyhow::anyhow!("Failed to get clipboard text"))),
    }
}
```

**Comment by ChurchTao** [comment]
具体看下这个
https://kaisery.github.io/trpl-zh-cn/ch04-02-references-and-borrowing.html

**Comment by ChurchTao** [comment]
应该没问题了吧，有问题重新打开这个issue即可
