### ISSUE TITLE
Bug: Cannot paste after writing image to clipboard (on Windows)

### ISSUE THREAD

**Issue by HuakunShen** [ChurchTao/clipboard-rs#17]
### The problem | 问题描述

After writing image to clipboard (with clipboard-rs) on Windows, I cannot paste the image in other applications.

### Release version | 版本

0.1.5

### Operating system | 操作系统

Win11

**Comment by HuakunShen** [comment]
Issue first mentioned in https://github.com/CrossCopy/tauri-plugin-clipboard/issues/21

**Comment by ChurchTao** [comment]
https://github.com/ChurchTao/clipboard-rs/pull/20
