### ISSUE TITLE
Bug: Cannot read clipboard image on MacOS for screenshots taken by certain apps

### ISSUE THREAD

**Issue by HuakunShen** [ChurchTao/clipboard-rs#19]
### The problem | 问题描述

Issue first mentioned in https://github.com/CrossCopy/tauri-plugin-clipboard/issues/21 by @Tester-957

Screenshots taken with Feishu/Lark can neither be detected nor read by clipboard-rs, while regular screenshots and screenshots taken by other apps like WeChat could be detected.

By running the sample code we can see that `ctx.get_image()` doesn't return Err, but the resulting image has a size of (0, 0)

<img src="https://github.com/ChurchTao/clipboard-rs/assets/33727687/45b21250-1cc1-4c91-bce4-663188122ccb" width="70%" />

### Release version | 版本

0.1.5

### Operating system | 操作系统

MacOS

**Comment by HuakunShen** [comment]
Bug located

Here is the available format for a regular screenshot: `["public.png", "Apple PNG pasteboard type", "public.tiff", "NeXT TIFF v4.0 pasteboard type"]`

Here is the available format for a Feishu screenshot `["public.tiff", "NeXT TIFF v4.0 pasteboard type"]`

Screenshot taken with Feishu somehow doesn't support PNG format, and only PNG is considered in the code https://github.com/ChurchTao/clipboard-rs/blob/7b23a6fecf05537d1f46e5745eafd88ecf7e4339/src/platform/macos.rs#L279

# Solution

`clipboard.dataForType(NSPasteboardTypeTIFF)` will return screenshots from Feishu.
TIFF is supported by both regular screenshot and Feishu screenshot (verified), so you could simply replace `NSPasteboardTypePNG` with `NSPasteboardTypeTIFF`
However, it might be prudent to handle both TIFF and PNG formats for `has()` and `get_image()`, ensuring compatibility across different scenarios. Supporting both formats is a safer approach.

**Comment by HuakunShen** [comment]
PR opened here by @ChurchTao https://github.com/ChurchTao/clipboard-rs/pull/16

Fixed by adding a check on the value of png and tiff. If there is no data, Err is returned.

**Comment by ChurchTao** [comment]
next version will be ok～
