### ISSUE TITLE
当写入html时，在Windows上长度似乎是有限制的，并且会被自动截断。截断的长度不固定

### ISSUE THREAD

**Issue by Tester-957** [ChurchTao/clipboard-rs#23]
### The problem | 问题描述

这是在另一个项目中提交的讨论：https://github.com/CrossCopy/tauri-plugin-clipboard/issues/29
🐛因为内容是从剪切板中读取出来的HTML，使用API原样写入时遇到这个限制。通过系统快捷键写入的html没有这个限制。
🤖我不确定这是否是Windows的限制还是BUG ~

### Release version | 版本

0.1.6

### Operating system | 操作系统

Windows 11

### Logs | 日志

Length (original): 132205
Length: 205

**Comment by ChurchTao** [comment]
收到，我试验一下，如果有问题我会快速修复
