### ISSUE TITLE
如何计算图像的哈希值？

### ISSUE THREAD

**Issue by ayangweb** [ChurchTao/clipboard-rs#25]
### The feature request | 需求描述

大佬，我是 Rust 新手，现在正在处理 `read_image` 拿到的图像的哈希值计算，以便将哈希值作为文件名称，这样可以避免重复复制相同的图片。我尝试使用 img_hash 库，但在参数传递时总是出错。希望能得到您的帮助，谢谢！

### Proposed solution | 解决方案

我主要就是想实现避免重复复制相同的图片，希望能得到您的帮助，提供一个实现思路，非常感谢！

**Comment by ChurchTao** [comment]
@ayangweb 我推荐你可以使用这个库，
> https://github.com/DoumanAsh/xxhash-rust

我写个简单的例子

现在配置中增加依赖：
`xxhash-rust = { version = "0.8.10", features = ["xxh3"] }`

```rust
use clipboard_rs::{common::RustImage, Clipboard, ClipboardContext};
use xxhash_rust::xxh3::xxh3_64;

fn main() {
	let ctx = ClipboardContext::new().unwrap();

	let img = ctx.get_image();

	match img {
		Ok(img) => {
			let hash = xxh3_64(&img.to_png().unwrap().get_bytes());
			let hash_str = format!("{:x}", hash);
			println!("hash={}", hash);
			println!("hash_str={}", hash_str);
		}
		Err(err) => {
			println!("err={}", err);
		}
	}
}
```

**Comment by ChurchTao** [comment]
图片在不同的格式，不同大小，hash肯定也是不同的，本质上是图片内容的字节数组不一样  `byte[]`

**Comment by ayangweb** [comment]
@ChurchTao 谢谢大佬的回复，我这边也是查阅了一下 rust 相关的知识，实现思路也是跟您的一致！

```rust
use std::{ hash::{Hash, Hasher}, };

let ctx = ClipboardContext::new().unwrap();

let image = ctx.get_image().unwrap();

let bytes = image.to_png().unwrap().get_bytes().to_vec();

let mut hasher = DefaultHasher::new();
bytes.hash(&mut hasher);
let hash = hasher.finish();
```

**Comment by ChurchTao** [comment]
嗯嗯，hash算法有快慢的，如果是很大的图，就需要考虑这个hash算法的速度了

**Comment by ayangweb** [comment]
> 嗯嗯，hash算法有快慢的，如果是很大的图，就需要考虑这个hash算法的速度了

哦哦，这个我暂时没有注意到，您推荐的 xxhash_rust 这个算法库比较快是吧 😁，我可以换上试试

**Comment by ayangweb** [comment]
> 图片在不同的格式，不同大小，hash肯定也是不同的，本质上是图片内容的字节数组不一样 `byte[]`

感谢大佬提醒，这让我想到了用缩略图计算哈希，果然又能快出将近 60% 的时间 🤗
