### ISSUE TITLE
如何获取复制内容的 app 来源

### ISSUE THREAD

**Issue by ayangweb** [ChurchTao/clipboard-rs#26]
### The feature request | 需求描述

大佬，您有没有推荐的方法能够在兼容各平台的情况下，获取复制内容的 app 来源啊！

### Proposed solution | 解决方案

希望大佬能指点迷津，谢谢😁

**Comment by ChurchTao** [comment]
据我所知目前比较合理的方案应该是，在程序运行中，监听当前活跃的窗口（这个在不同的系统下，实现方式不同），然后再监听剪贴板变化，发生变化时，同时拿上当前活跃的窗口信息（比如进程id，程序路径，icon之类的），这里有个问题，就是延迟的问题，因为程序得知剪贴板变化不是实时的，一般来说，有100ms-1000ms的延迟（这看你代码怎么写），所以我们应该提前做好当前活跃窗口的缓存，当窗口变化时更新缓存，然后当剪贴板变化时，直接获取缓存，这样可以避免（当剪贴板变化后迅速切换app时，获取的app是切换后的）

**Comment by ChurchTao** [comment]
@ayangweb 也许你可以尝试使用这个库

https://github.com/dimusic/active-win-pos-rs

**Comment by ayangweb** [comment]
> @ayangweb 也许你可以尝试使用这个库
> 
> https://github.com/dimusic/active-win-pos-rs

真不错，这个应该是可以解决我的困扰了，我会研究一下它的用法，不过它貌似不支持图标的获取，不过问题不大，应该可以通过进程信息来获取图标！非常感谢！😁

**Comment by ChurchTao** [comment]
他这个库，封装了跨平台获取，确实很方便，但是主动获取就一定存在延迟，这个你可以自行按照自己设计的应用去设定。

另外也提供你一个实时的思路：

比如要实时获取MacOS中有这样API，向系统添加一个观察者`NSWorkspace.didActivateApplicationNotification`，当活跃窗口发生变化时，他会实时通知你。此时你获取`active_window`后放入缓存, 缓存的更新就会很准，很及时，并且也会降低一直去获取导致的性能损耗。

https://developer.apple.com/documentation/foundation/nsnotificationcenter/1415360-addobserver?language=objc

**Comment by ChurchTao** [comment]
至于另外系统怎么实现，你可以去看他这个库的代码，或者去查询相关系统的API，这就是跨平台开发一直会有的难题

**Comment by ayangweb** [comment]
> 他这个库，封装了跨平台获取，确实很方便，但是主动获取就一定存在延迟，这个你可以自行按照自己设计的应用去设定。
> 
> 另外也提供你一个实时的思路：
> 
> 比如要实时获取MacOS中有这样API，向系统添加一个观察者`NSWorkspace.didActivateApplicationNotification`，当活跃窗口发生变化时，他会实时通知你。此时你获取`active_window`后放入缓存, 缓存的更新就会很准，很及时，并且也会降低一直去获取导致的性能损耗。
> 
> https://developer.apple.com/documentation/foundation/nsnotificationcenter/1415360-addobserver?language=objc

好的好的，谢谢，我都研究研究，反正这个东西不着急，就是看看有没有合适的方案😁

**Comment by ayangweb** [comment]
> 至于另外系统怎么实现，你可以去看他这个库的代码，或者去查询相关系统的API，这就是跨平台开发一直会有的难题

确实，这让本不会 rust 的我更是雪上加霜😂

**Comment by ChurchTao** [comment]
暂时不考虑在这个库加入 app来源等功能
