### ISSUE TITLE
在微信选中文字就会触发 `on_clipboard_change`

### ISSUE THREAD

**Issue by ayangweb** [ChurchTao/clipboard-rs#27]
### The problem | 问题描述

大佬，忽然发现在微信上随便选几个字，但是不复制，仍然会触发 `on_clipboard_change` 事件，但是复制的内容又没发生变化，这是什么情况啊！🤨

https://github.com/ChurchTao/clipboard-rs/assets/75017711/286b45ee-b83c-4350-ad6a-9c9762ccdafe

### Release version | 版本

0.1.7

### Operating system | 操作系统

MacOS M1 Pro Sonoma 14.4

**Comment by ayangweb** [comment]
大佬，刚才随便乱点的时候发现双击空白处也会触发 `on_clipboard_change` 🤔

https://github.com/ChurchTao/clipboard-rs/assets/75017711/81f01031-8aa7-4a68-b3a1-ed6a12e4adfc

**Comment by ayangweb** [comment]
上述问题只在 MacOS 复现，Windows 系统没有这些问题！😁

**Comment by ChurchTao** [comment]
有没有可能是你安装的什么软件造成的？我看你选中时会出现一个弹框

**Comment by ayangweb** [comment]
> 有没有可能是你安装的什么软件造成的？我看你选中时会出现一个弹框

我去，果然是这个 app 造成的，小丑了🤡，感谢感谢
