### ISSUE TITLE
重新复制 HTML 时，部分软件粘贴失效

### ISSUE THREAD

**Issue by ayangweb** [ChurchTao/clipboard-rs#28]
### The problem | 问题描述

大佬，我在对 `get_html()` 获取到的内容，原封不动的调用 `set_html(html)`，但是发现这样的话在 vscode、微信、谷歌浏览器（目前只发现这几个）粘贴都是失效的，但是其它同类型剪切板 app 重新复制粘贴是没有问题的！这个不知道是啥情况，还望大佬解惑😁

### Release version | 版本

0.1.7

### Operating system | 操作系统

MacOS M1 Pro Sonoma 14.4

**Comment by ChurchTao** [comment]
贴下代码demo，然后说一下操作流程吧，我好复现一下

**Comment by ayangweb** [comment]
> 贴下代码demo，然后说一下操作流程吧，我好复现一下

OK，等我抽空写个 demo + 视频

**Comment by ChurchTao** [comment]
哦，我知道了，set_html 只会设置 html格式的值，并不会设置纯文本格式的值，而你再次粘贴时，所以粘贴时无内容

你可以使用下方 api，去设置多格式的值
> https://github.com/ChurchTao/clipboard-rs/blob/0329c0d511636cd873aac64994f9867c75ef00e4/examples/multi.rs#L14

**Comment by ayangweb** [comment]
> 哦，我知道了，set_html 只会设置 html格式的值，并不会设置纯文本格式的值，而你再次粘贴时，所以粘贴时无内容
> 
> 你可以使用下方 api，去设置多格式的值
> 
> > https://github.com/ChurchTao/clipboard-rs/blob/0329c0d511636cd873aac64994f9867c75ef00e4/examples/multi.rs#L14

好的，谢谢，我研究下😁

**Comment by ayangweb** [comment]
> 哦，我知道了，set_html 只会设置 html格式的值，并不会设置纯文本格式的值，而你再次粘贴时，所以粘贴时无内容
> 
> 你可以使用下方 api，去设置多格式的值
> 
> > https://github.com/ChurchTao/clipboard-rs/blob/0329c0d511636cd873aac64994f9867c75ef00e4/examples/multi.rs#L14

谢谢，亲测可行！😁

**Comment by ayangweb** [comment]
@ChurchTao 大佬，是这样使用吗？我在这样复制的时候粘贴出来的 html 是没有格式的，是纯文本🤔

```rust
#[command]
async fn write_html(
    manager: State<'_, ClipboardManager>,
    text: String,
    html: String,
) -> Result<()> {
    println!("{text}\n\n\n{html}");

    let contents = vec![ClipboardContent::Text(text), ClipboardContent::Html(html)];

    manager.context.set(contents).unwrap();

    Ok(())
}
```

**Comment by ChurchTao** [comment]
贴下你存储时的逻辑

**Comment by ayangweb** [comment]
> 贴下你存储时的逻辑

```rs
#[command]
async fn read_html(manager: State<'_, ClipboardManager>) -> Result<String> {
    Ok(manager.context.get_html().unwrap())
}
```

```ts
/**
 * 读取 HTML 内容
 */
export const readHTML = async () => {
	const html = await invoke<string>(CLIPBOARD_PLUGIN.READ_HTML);

	const size = html2text(html).length;

	return {
		size,
		value: html,
	};
};
```

**Comment by ChurchTao** [comment]
html2text 内容看下

**Comment by ChurchTao** [comment]
我试了一下，原模原样的 text set 回去是正常带换行的。

那么我们就能排除是 API 的问题，是否可以往这个 html2text 上怀疑一下是不是格式发生了什么变化

**Comment by ChurchTao** [comment]
我感觉你把 html 和 text 放两个字段会好一点，你现在应该是其实只在页面上存了一个 html

**Comment by ayangweb** [comment]
> 我感觉你把 html 和 text 放两个字段会好一点，你现在应该是其实只在页面上存了一个 html

存是我有考虑的，搜索的时候只搜索纯文本会好一些！但是我现在发现了问题所在！

复制内容：
```js
const a = 1;
const b = 2;
```

剪切板的 html 内容：
```js
const a = 1;
const b = 2;
```

<meta charset='utf-8'><div style="color: #abb2bf;background-color: #23272e;font-family: JetBrains Mono, Menlo, Monaco, 'Courier New', monospace, Menlo, Monaco, 'Courier New', monospace;font-weight: normal;font-size: 13px;line-height: 20px;white-space: pre;"><div><span style="color: #c678dd;font-style: italic;">const</span><span style="color: #abb2bf;"> </span><span style="color: #e5c07b;">a</span><span style="color: #abb2bf;"> </span><span style="color: #56b6c2;font-style: italic;">=</span><span style="color: #abb2bf;"> </span><span style="color: #d19a66;">1</span><span style="color: #abb2bf;">;</span></div><div><span style="color: #c678dd;font-style: italic;">const</span><span style="color: #abb2bf;"> </span><span style="color: #e5c07b;">b</span><span style="color: #abb2bf;"> </span><span style="color: #56b6c2;font-style: italic;">=</span><span style="color: #abb2bf;"> </span><span style="color: #d19a66;">2</span><span style="color: #abb2bf;">;</span></div><br></div>

**Comment by ayangweb** [comment]
> 我试了一下，原模原样的 text set 回去是正常带换行的。
> 
> 那么我们就能排除是 API 的问题，是否可以往这个 html2text 上怀疑一下是不是格式发生了什么变化

感谢大佬，终于摆平这个问题了 🥳
