### ISSUE TITLE
[bug] windows 系统 html 写入剪切板的问题

### ISSUE THREAD

**Issue by ayangweb** [ChurchTao/clipboard-rs#32]
### The problem | 问题描述

在 Windows 系统中，我发现一个奇怪的问题：当我先使用 `write_files` 复制一个文件时，粘贴操作是正常的；但随后如果我使用 `write_html` 复制 HTML 内容，粘贴时依然会是之前复制的文件！而在 MacOS 上，这个现象并不会出现。

```rust
#[command]
async fn write_files(manager: State<'_, ClipboardManager>, value: Vec<String>) -> Result<()> {
    manager.context.set_files(value).unwrap();

    Ok(())
}

#[command]
async fn write_html(
    manager: State<'_, ClipboardManager>,
    text: String,
    html: String,
) -> Result<()> {
    let contents = vec![ClipboardContent::Text(text), ClipboardContent::Html(html)];

    manager.context.set(contents).unwrap();

    Ok(())
}
```

### Release version | 版本

0.1.7

### Operating system | 操作系统

Windows 11

### Logs | 日志

https://github.com/user-attachments/assets/306256ee-c99a-44e8-bc88-eb2076a29f60

**Comment by ChurchTao** [comment]
了解了，确实是我在实现同一个API时，不同操作系统的逻辑没有对齐，在MacOS中我会先调用clear，而win中并没有这么做，如果你紧急的话，你可以在你自己的逻辑中，手动先调用clear，再继续逻辑，这个bug我会在下个版本中修复，但是由于改动偏少，我也许不会快速更新版本，可能攒一下

**Comment by ayangweb** [comment]
> 了解了，确实是我在实现同一个API时，不同操作系统的逻辑没有对齐，在MacOS中我会先调用clear，而win中并没有这么做，如果你紧急的话，你可以在你自己的逻辑中，手动先调用clear，再继续逻辑，这个bug我会在下个版本中修复，但是由于改动偏少，我也许不会快速更新版本，可能攒一下

可以的，我也不着急，等新版本就好！

**Comment by ayangweb** [comment]
或许我可以贡献一个 pr，能大概告诉我怎么做吗？我没看懂源码😥

**Comment by ChurchTao** [comment]
https://github.com/ChurchTao/clipboard-rs/blob/bb245413f297d724e019fe9c67ba50926f684f42/src/platform/win.rs#L362

**Comment by ayangweb** [comment]
> https://github.com/ChurchTao/clipboard-rs/blob/bb245413f297d724e019fe9c67ba50926f684f42/src/platform/win.rs#L362

我看到这里，但是我不确定我要在哪里写 clear 方法😁

**Comment by ChurchTao** [comment]
@ayangweb 
`v0.1.9` 发布了，辛苦帮我测试一下，顺便回归一下windows环境下的图片读取，写入问题

**Comment by ayangweb** [comment]
> @ayangweb `v0.1.9` 发布了，辛苦帮我测试一下，顺便回归一下windows环境下的图片读取，写入功能

大佬高效率，我测试下前者，回归一下是什么意思？顺便测试一下 windows 系统的图片的读取和写入吗？

**Comment by ChurchTao** [comment]
> > @ayangweb `v0.1.9` 发布了，辛苦帮我测试一下，顺便回归一下windows环境下的图片读取，写入功能
> 
> 大佬高效率，我测试下前者，回归一下是什么意思？顺便测试一下 windows 系统的图片的读取和写入吗？

嗯嗯，我手头没有window机子，回归测试就是说改动可能会影响到别的功能，需要回过头去测试一下那些功能，麻烦你了

**Comment by ayangweb** [comment]
> > > @ayangweb `v0.1.9` 发布了，辛苦帮我测试一下，顺便回归一下windows环境下的图片读取，写入功能
> > 
> > 
> > 大佬高效率，我测试下前者，回归一下是什么意思？顺便测试一下 windows 系统的图片的读取和写入吗？
> 
> 嗯嗯，我手头没有window机子，回归测试就是说改动可能会影响到别的功能，需要回过头去测试一下那些功能，麻烦你了

我问的问题解决了！其它问题暂时没有出现，有了再反馈哈。谢谢大佬！

**Comment by ayangweb** [comment]
> 我问的问题解决了！不过 windows 和 macos 写入同一张照片时，windows 要慢 macos 2s 左右，这个问题有好的解决方案吗？其它问题暂时没有出现，有了再反馈哈。谢谢大佬！

特别慢也有可能是我虚拟机的问题，我让我朋友空了也测试一下写入图片的速度！

**Comment by ayangweb** [comment]
> > 我问的问题解决了！不过 windows 和 macos 写入同一张照片时，windows 要慢 macos 2s 左右，这个问题有好的解决方案吗？其它问题暂时没有出现，有了再反馈哈。谢谢大佬！
> 
> 特别慢也有可能是我虚拟机的问题，我让我朋友空了也测试一下写入图片的速度！

实在影响体验的话，我再来给您反馈😁

**Comment by ChurchTao** [comment]
👌
