### ISSUE TITLE
设置剪切板时图片失真，像素偏移

### ISSUE THREAD

**Issue by ningnao** [ChurchTao/clipboard-rs#35]
### The problem | 问题描述

截图工具 pixpin

原图：
![1721711358842](https://github.com/user-attachments/assets/4a6db03e-1810-48ca-b368-c047870f9986)
设置剪切板后：
![1721711376563](https://github.com/user-attachments/assets/c5827939-497b-4ddb-9278-ed961fbbd788)

使用ClipboardWatcherContext监听剪切板变化，然后将获取到的图片立刻set回去，此时图片失真

``` rust
impl ClipboardHandler for Manager {
    fn on_clipboard_change(&mut self) {
        if self.ctx.has(ContentFormat::Text) {
            if let Ok(result) = self.ctx.get_text() {
                info!("复制了文字{}", result);
            }
        } else if self.ctx.has(ContentFormat::Image) {
            if let Ok(result) = self.ctx.get_image() {
                info!("复制了图片");
                let _ = self.ctx.set_image(result);
            }
        }
    }
}
```

### Release version | 版本

0.1.9

### Operating system | 操作系统

windows 11

### Logs | 日志

None

**Comment by ChurchTao** [comment]
收到，
1. 提供一下原图
2. 然后辛苦提供一下，截图触发时 打印一下 `ctx.available_format()`，然后 `set_image()` 后，再打印一下`ctx.available_format()`

**Comment by ningnao** [comment]
原图：
![6ef51bd217f0709eb49219addc173701](https://github.com/user-attachments/assets/66dde516-2987-4d68-a2b8-2a2563c01f69)

前
```
Ok(["DataObject", "CF_DIBV5", "CF_DIB", "PixPinData", "image/png", "image/bmp", "image/cur", "image/icns", "ima
ge/ico", "image/jpeg", "image/jpg", "image/pbm", "image/pgm", "image/ppm", "image/tif", "image/tiff", "image/wbmp", "image/webp", "image/xbm", "image/xpm", "Ole Private Data", "CF_BITMAP"])
```
后
```
Ok(["PNG", "CF_DIB", "CF_DIBV5", "CF_BITMAP"])
```

**Comment by ayangweb** [comment]
@ChurchTao 大佬，同问！

https://github.com/ayangweb/EcoPaste/issues/221

我的 app 也有这个问题！

[`read_image`](https://github.com/ayangweb/EcoPaste/blob/da8b0b311e30e117a18df88426593411114f859f/src-tauri/src/plugins/clipboard.rs#L135)

[`wtite_image`](https://github.com/ayangweb/EcoPaste/blob/da8b0b311e30e117a18df88426593411114f859f/src-tauri/src/plugins/clipboard.rs#L192)

**Comment by ChurchTao** [comment]
我手头目前没有windows机器，等我周末在家研究一下，估计是格式转化的时候有问题

**Comment by ayangweb** [comment]
> 我手头目前没有windows机器，等我周末在家研究一下，估计是格式转化的时候有问题

好嘞🥰

**Comment by ChurchTao** [comment]
@ayangweb @ningnao 这个问题修了，是因为png格式的图片颜色格式有很多种，但是 bitmapV5 的颜色格式写入时需要指定为rgba8所以有问题。

**Comment by ayangweb** [comment]
> @ayangweb @ningnao 这个问题修了，是因为png格式的图片颜色格式有很多种，但是 bitmapV5 的颜色格式写入时需要指定为rgba8所以有问题。

🥳

**Comment by ayangweb** [comment]
> @ayangweb @ningnao 这个问题修了，是因为png格式的图片颜色格式有很多种，但是 bitmapV5 的颜色格式写入时需要指定为rgba8所以有问题。

🎉

**Comment by ChurchTao** [comment]
这个问题很蛋疼，我测试的时候是往wps和画图中粘贴，结果是对的，因为那两个app估计是优先读取png，而微信、飞书这类读取的是bitmap

**Comment by ayangweb** [comment]
怪不得，有些 app 正常，有些 app 不正常，大佬给力啊👏

**Comment by ningnao** [comment]
@ChurchTao 

看起来图像失真的问题解决了，但像素偏移的问题还在
原图还是上面那张图
截图工具 pixpin
![1722079568141](https://github.com/user-attachments/assets/3951197f-cfc4-4f41-9d7b-29d4642762fc)

有一个细节，复制后的图片粘贴到微信中才会偏移，试了试QQ和浏览器没问题

**Comment by ningnao** [comment]
同时似乎跟截图工具无关，尝试了windows自带的截图工具，微信带的截图工具，均能浮现

**Comment by ChurchTao** [comment]
卧槽真的诶，我竟然没发现

**Comment by ayangweb** [comment]
@ChurchTao @ningnao 大佬们对 windows 系统的原生的 api 熟悉吗？我现在遇到个问题，windows 上如果在固定窗口之后就没有办法完成自动粘贴了！

代码位置：
https://github.com/ayangweb/EcoPaste/blob/de4ab2842e785a2b6ba6cbeabd0438369f6990af/src-tauri/src/plugins/paste.rs#L32

我想到两种解决方案：
1. 像 macos 一样实时监听窗口聚焦状态的变化，把窗口进程 id 存起来！https://github.com/ayangweb/EcoPaste/blob/master/src-tauri/src/core/app/macos.rs
2. 获取 EcoPaste 下面的另一个窗口！（代码如下，未生效）

```rs
#[cfg(target_os = "windows")]
fn focus_previous_window() {
    use std::ptr;
    use winapi::um::winuser::{EnumWindows, GetForegroundWindow, GetWindowThreadProcessId, SetForegroundWindow, IsWindowVisible, GetWindow, GW_HWNDNEXT};
    use winapi::shared::windef::HWND;
    use std::mem::transmute;

    unsafe {
        let foreground_window = GetForegroundWindow();

        if foreground_window.is_null() {
            println!("Could not get active window");
            return;
        }

        // Get the next window in the Z-order after the foreground window
        let next_window = GetWindow(foreground_window, GW_HWNDNEXT);

        if next_window.is_null() {
            println!("Could not get next window");
            return;
        }

        if SetForegroundWindow(next_window) == 0 {
            println!("Could not focus on window");
        }
    }
}

fn main() {
    focus_previous_window();
}
```

**Comment by ChurchTao** [comment]
@ningnao OK了

**Comment by ChurchTao** [comment]
> @ChurchTao @ningnao 大佬们对 windows 系统的原生的 api 熟悉吗？我现在遇到个问题，windows 上如果在固定窗口之后就没有办法完成自动粘贴了！
> 
> 代码位置： https://github.com/ayangweb/EcoPaste/blob/de4ab2842e785a2b6ba6cbeabd0438369f6990af/src-tauri/src/plugins/paste.rs#L32
> 
> 我想到两种解决方案：
> 
> 1. 像 macos 一样实时监听窗口聚焦状态的变化，把窗口进程 id 存起来！https://github.com/ayangweb/EcoPaste/blob/master/src-tauri/src/core/app/macos.rs
> 2. 获取 EcoPaste 下面的另一个窗口！（代码如下，未生效）
> 
> ```rust
> #[cfg(target_os = "windows")]
> fn focus_previous_window() {
>     use std::ptr;
>     use winapi::um::winuser::{EnumWindows, GetForegroundWindow, GetWindowThreadProcessId, SetForegroundWindow, IsWindowVisible, GetWindow, GW_HWNDNEXT};
>     use winapi::shared::windef::HWND;
>     use std::mem::transmute;
> 
>     unsafe {
>         let foreground_window = GetForegroundWindow();
> 
>         if foreground_window.is_null() {
>             println!("Could not get active window");
>             return;
>         }
> 
>         // Get the next window in the Z-order after the foreground window
>         let next_window = GetWindow(foreground_window, GW_HWNDNEXT);
> 
>         if next_window.is_null() {
>             println!("Could not get next window");
>             return;
>         }
> 
>         if SetForegroundWindow(next_window) == 0 {
>             println!("Could not focus on window");
>         }
>     }
> }
> 
> fn main() {
>     focus_previous_window();
> }
> ```

我也不熟winapi，可以去查下官方的api，我浅浅的看了一下，没试过，你看下这个
https://learn.microsoft.com/zh-cn/previous-versions/windows/desktop/directmanipulation/direct-manipulation-portal

**Comment by ayangweb** [comment]
> > @ChurchTao @ningnao 大佬们对 windows 系统的原生的 api 熟悉吗？我现在遇到个问题，windows 上如果在固定窗口之后就没有办法完成自动粘贴了！
> > 代码位置： https://github.com/ayangweb/EcoPaste/blob/de4ab2842e785a2b6ba6cbeabd0438369f6990af/src-tauri/src/plugins/paste.rs#L32
> > 我想到两种解决方案：
> > 
> > 1. 像 macos 一样实时监听窗口聚焦状态的变化，把窗口进程 id 存起来！https://github.com/ayangweb/EcoPaste/blob/master/src-tauri/src/core/app/macos.rs
> > 2. 获取 EcoPaste 下面的另一个窗口！（代码如下，未生效）
> > 
> > ```rust
> > #[cfg(target_os = "windows")]
> > fn focus_previous_window() {
> >     use std::ptr;
> >     use winapi::um::winuser::{EnumWindows, GetForegroundWindow, GetWindowThreadProcessId, SetForegroundWindow, IsWindowVisible, GetWindow, GW_HWNDNEXT};
> >     use winapi::shared::windef::HWND;
> >     use std::mem::transmute;
> > 
> >     unsafe {
> >         let foreground_window = GetForegroundWindow();
> > 
> >         if foreground_window.is_null() {
> >             println!("Could not get active window");
> >             return;
> >         }
> > 
> >         // Get the next window in the Z-order after the foreground window
> >         let next_window = GetWindow(foreground_window, GW_HWNDNEXT);
> > 
> >         if next_window.is_null() {
> >             println!("Could not get next window");
> >             return;
> >         }
> > 
> >         if SetForegroundWindow(next_window) == 0 {
> >             println!("Could not focus on window");
> >         }
> >     }
> > }
> > 
> > fn main() {
> >     focus_previous_window();
> > }
> > ```
> 
> 我也不熟winapi，可以去查下官方的api，我浅浅的看了一下，没试过，你看下这个，直接对之前那个窗口 `SendInput` https://learn.microsoft.com/en-us/dotnet/api/envdte.commandwindow.sendinput?view=visualstudiosdk-2022

好的，感谢大佬，我看一下

**Comment by ayangweb** [comment]
https://github.com/EcoPasteHub/EcoPaste/issues/1009

佬，windows 依然存在这个问题。
