### ISSUE TITLE
[bug] windows 复制内容频繁崩溃

### ISSUE THREAD

**Issue by ayangweb** [ChurchTao/clipboard-rs#39]
### The problem | 问题描述

佬，帮忙看看 windows 复制崩溃的问题，一点眉目都没有，呜呜呜😭

- https://github.com/ayangweb/EcoPaste/issues/303
- https://github.com/ayangweb/EcoPaste/issues/251

### Release version | 版本

0.1.11

### Operating system | 操作系统

windows

### Logs | 日志

![image](https://github.com/user-attachments/assets/21fb51c2-f443-4881-a981-92cd8f68c042)

**Comment by ChurchTao** [comment]
你自己能重现吗？

**Comment by ayangweb** [comment]
在我的 windows 复制机会浏览器的链接就崩溃了

**Comment by ChurchTao** [comment]
你在dev的情况下，有看到任何报错日志吗？

**Comment by ayangweb** [comment]
貌似只有在 build 环境会崩溃，dev 环境一点毛病没有😭

最近反馈的 app 无限重启的 bug 也是 build 环境的问题，dev 没问题

**Comment by ayangweb** [comment]
不过日志我得看一下，我不经常使用 windows 不太懂 windows 这些🫣

**Comment by ChurchTao** [comment]
先看下，能不能在dev环境下复现，然后观察有没有可疑日志，
tauri可以以release模式运行
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/3073bd95-24cc-486d-9ec8-b0d9df9f0f55">

**Comment by ayangweb** [comment]
> 先看下，能不能在dev环境下复现，然后观察有没有可疑日志，
> tauri可以以release模式运行

好嘞，我试试

**Comment by ElluIFX** [comment]
![image](https://github.com/user-attachments/assets/5e3e37e9-560e-4619-879a-ad7d42e691f8)

本来打算通过python脚本监听剪贴板变化和ecopaste进程结束的时间来找到触发崩溃的复制项目的，结果意外的发现了复现崩溃的方法

**简单来说就是在windows上，如果其他程序已经打开剪贴板了，或者在ecopaste读写剪贴板期间尝试打开剪贴板，就会直接导致ecopaste crash**

因此在这个测试里面，这个监听脚本反而成了ecopaste频繁崩溃的源头

> 貌似只有在 build 环境会崩溃，dev 环境一点毛病没有😭

由上述原因，可以怀疑是dev环境调试器介入并截获处理了这个读写冲突的异常，但是release环境下就会触发

**Comment by ayangweb** [comment]
@ChurchTao 佬，空了看下楼上大佬的回复，我没看懂啥情况🥹

**Comment by ChurchTao** [comment]
> @ChurchTao 佬，空了看下楼上大佬的回复，我没看懂啥情况🥹

你 release模式 调试没有复现？

**Comment by ayangweb** [comment]
> > @ChurchTao 佬，空了看下楼上大佬的回复，我没看懂啥情况🥹
> 
> 你 release模式 调试没有复现？

我有点忙，今天我抽空试一下🫣

**Comment by ChurchTao** [comment]
> ![image](https://private-user-images.githubusercontent.com/31679332/356258160-5e3e37e9-560e-4619-879a-ad7d42e691f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjkwNzUsIm5iZiI6MTcyMzE2ODc3NSwicGF0aCI6Ii8zMTY3OTMzMi8zNTYyNTgxNjAtNWUzZTM3ZTktNTYwZS00NjE5LTg3OWEtYWQ3ZDQyZTY5MWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDAxNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNmE4MTI4ZDUzMWUyYTUxNTkzYjVjMTUzNDVhZTJjNDQxMDlkNTI1OTUzNDJkZDIxMWUxYzYzNTg4NWVjMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qEqwOHDSccotac-oxwUaIZ2b_-DQtkDaK4iT_JMdhr4)
> 
> 本来打算通过python脚本监听剪贴板变化和ecopaste进程结束的时间来找到触发崩溃的复制项目的，结果意外的发现了复现崩溃的方法
> 
> **简单来说就是在windows上，如果其他程序已经打开剪贴板了，或者在ecopaste读写剪贴板期间尝试打开剪贴板，就会直接导致ecopaste crash**
> 
> 因此在这个测试里面，这个监听脚本反而成了ecopaste频繁崩溃的源头
> 
> > 貌似只有在 build 环境会崩溃，dev 环境一点毛病没有😭
> 
> 由上述原因，可以怀疑是dev环境调试器介入并截获处理了这个读写冲突的异常，但是release环境下就会触发

@ElluIFX @ayangweb
这是很显而易见的问题，window中无论谁持有了剪贴板，别人都无法获得剪贴板，崩溃本身都是因为你没有处理好 Err 或者 存在Panic才会导致崩溃。我举个例子
https://github.com/ayangweb/EcoPaste/blob/213e448b70a17daea96ff8eaa99204b77474b109/src-tauri/src/plugins/clipboard.rs#L198

如果这里的 `get_text()` 报出了一个Err，你的 `unwrap` 会导致什么你清楚吗？

**Comment by ChurchTao** [comment]
我建议你在写rust的时候，只有在你断言这个地方不可能有问题的情况，才能用 `unwrap()` , 否则出各种问题你都无法处理。
就好像你在写 js 或者 java的时候，某些时候也会使用  try catch 去处理异常

**Comment by ayangweb** [comment]
> 我建议你在写rust的时候，只有在你断言这个地方不可能有问题的情况，才能用 `unwrap()` , 否则出各种问题你都无法处理。 就好像你在写 js 或者 java的时候，某些时候也会使用 try catch 去处理异常

呜呜呜，我知道了，rust 功力还是不够🫣我下来再把代码优化优化

**Comment by ChurchTao** [comment]
出现异常的处理方式有很多种，常见的
1. 不太要紧的毛病，看下能不能降级处理，本来导致的崩溃，我返回一个空字符串行不行，或者直接 return 不执行了行不行，如果可以降级，就降级处理，顺便打个日志，上报一下
2. 比较重要的毛病，可以降级处理，但是用户需要感知，否则用户就会感觉到这个bug，那就触发一个反馈，告知用户，顺便打个日志，上报一下
3. 很重要的毛病，无法降级处理，如果这样执行下去，或者执行一半结束，会导致脏数据，或者无法挽回的问题，那就崩溃，或者说体验好一点的话也可以和第二个一样处理去回滚之前的操作和数据，然后奔溃提醒，然后上报日志。

总的来说，别人设计一个库的时候，API告诉你有可能会有某种异常存在，你如果忽视了它，那你的程序肯定就存在某种隐患。

加油⛽️，抽空去看下rust官网教程 https://kaisery.github.io/trpl-zh-cn/ch09-00-error-handling.html

**Comment by ayangweb** [comment]
好嘞，谢谢佬！我没学过 rust，哈哈，我学习一下这个报错的处理🌹
