### ISSUE TITLE
[bug] 写入富文本时会多写入一次

### ISSUE THREAD

**Issue by ayangweb** [ChurchTao/clipboard-rs#44]
### The problem | 问题描述

写入时传参和前端解析都没有问题，但是粘贴的时候就如下视频所示！

https://github.com/user-attachments/assets/71ece973-2f9c-4735-b7a5-681e3b4a36fb

### Release version | 版本

0.2.0

### Operating system | 操作系统

MacOS

**Comment by ChurchTao** [comment]
问题应该不是出在写入值的问题，应该在触发粘贴的时候，如果写入值有问题的话，我的ci里的test就过不去了。

你可以本地跑下这个demo：
https://github.com/ChurchTao/clipboard-rs/blob/master/examples/multi.rs
观察一下剪贴板内的值的变化，写入完之后，手动自己去粘贴一下看看

**Comment by ayangweb** [comment]
> 观察一下剪贴板内的值的变化，写入完之后，手动自己去粘贴一下看看

也对，我手动复制粘贴一下试试！
