### ISSUE TITLE
写到剪贴板的图片粘贴到 微信|钉钉输入框时颜色会变得很奇怪

### ISSUE THREAD

**Issue by zerooverture** [ChurchTao/clipboard-rs#49]
### The problem | 问题描述

写到剪贴板的图片粘贴到 微信|钉钉输入框时颜色会变得很奇怪：搜的其他issue提供的图片
![4](https://github.com/user-attachments/assets/d9a93ada-8a77-48b1-af3f-b668bf8a0976)
上面是原图，使用剪贴板粘贴后如果再用读取剪贴板并且保存到文件就是正常的，但是如果直接粘贴到微信或者钉钉的输入框中就变得很奇怪
![微信截图_20241008145129](https://github.com/user-attachments/assets/7eb828d5-d202-46a6-875c-b6eabdaad7ae)

使用代码
```
    let f = RustImageData::from_path("C:\\Users\\zero\\Downloads\\4.png").unwrap();
    ctx.set_image(f).expect("TODO: panic message");
```

available_formats :
set_image 前：["CF_BITMAP", "CF_DIB", "CF_DIBV5"]
set_image 后：["PNG", "CF_BITMAP", "CF_DIB", "CF_DIBV5"]

### Release version | 版本

0.2.1

### Operating system | 操作系统

windows 11

**Comment by zerooverture** [comment]
已经解决了 因为 qq 和微信需要特别处理图片格式

**Comment by ChurchTao** [comment]
> 已经解决了 因为 qq 和微信需要特别处理图片格式

你是怎么处理的？可以分享下看看吗

**Comment by zerooverture** [comment]
> > 已经解决了 因为 qq 和微信需要特别处理图片格式
> 
> 你是怎么处理的？可以分享下看看吗 @zerooverture

不要用 set_image  
改成把图片储存到文件，之后用
`clipboard_win::raw::set_file_list_with` 把文件路径插入就可以了，注意不要用 clipboard::Clipboard::set_files

另外可以扩展以下数据格式 作为完整支持  参考代码如下(注意，只支持Windows，mac的我还没尝试，应该不需要处理)：

```

static CF_QQ: &str = "QQ_Unicode_RichEdit_Format";
static CF_HTML: &str = "HTML Format";
// static CF_PNG: &str = "PNG";

pub type Result<T> = std::result::Result<T, Box<dyn Error + Send + Sync + 'static>>;

fn set_buffer(format: &str, buffer: Vec<u8>) -> Result<()> {
    let format_uint = clipboard_win::register_format(format);
    if format_uint.is_none() {
        return Err("register format error".into());
    }
    let format_uint = format_uint.unwrap().get();
    let res = set_without_clear(format_uint, &buffer);
    if res.is_err() {
        return Err("set buffer error".into());
    }
    Ok(())
}


pub fn tencent(png_path: &str) -> Result<()> {
    let qq_format = format!("<QQRichEditFormat><Info version=\"1001\"></Info><EditElement type=\"1\" filepath=\"{}\" shortcut=\"\"></EditElement></QQRichEditFormat>", png_path);

    let html_format = format!("<html>\n<body>\n<!--StartFragment--><img src=\"file:///{}\"><!--EndFragment-->\n</body>\n</html>", png_path);

    println!("{}", png_path);

    let image = RustImageData::from_path(png_path)?;

    let _clip = ClipboardWin::new_attempts(10)
        .map_err(|code| format!("Open clipboard error, code = {}", code));

    let res = clipboard_win::empty();
    if let Err(e) = res {
        return Err(format!("Empty clipboard error, code = {}", e).into());
    }

    set_buffer(CF_QQ, qq_format.as_bytes().to_vec())?;
    set_buffer(CF_HTML, html_format.as_bytes().to_vec())?;
    
    let mut v: Vec<String> = Vec::new();
    v.push(png_path.parse().unwrap());
    set_file_list_with(&v, options::NoClear).expect("TODO: panic message");

    let bmp = image
        .to_bitmap()
        .map_err(|e| format!("to bitmap error, code = {}", e))?;

    let _ = set_bitmap_with(bmp.get_bytes(), options::NoClear)
        .map_err(|e| format!("set image error, code = {}", e))?;


    Ok(())
}
```


按照上述方式生成的剪贴板数据如下：
Id		Name						HandleType	Size			Index
2		CF_BITMAP					Bitmap		0			4	
8		CF_DIB						Memory		1,360,084		5	
15		CF_HDROP					Memory		164			3	
17		CF_DIBV5						Memory		1,360,168		6	
49407	HTML Format					Memory		158			2	
49961	QQ_Unicode_RichEdit_Format	Memory		195			1

其中上述 CF_BITMAP CF_DIB CF_DIBV5 为原始图片数据，但实际上会出现上面的色差问题，
只需要有一条 CF_HDROP 就可以支持粘贴到 qq weixin 钉钉

**Comment by zerooverture** [comment]
只有通过qq右键复制图片的时候才会是上面发的那种

事实上 qq 和微信本身的截图 也只有下面这些，但是粘贴到其他软件不会有色差，不确定内部如何处理的，我对这方面不了解，只能大佬自己研究了，不过目前windows按照上面的方式基本能解决问题了
2	CF_BITMAP	Bitmap	0	1	
8	CF_DIB	Memory	1,444,508	2	
17	CF_DIBV5	Memory	1,444,592	3

**Comment by ChurchTao** [comment]
> 只有通过qq右键复制图片的时候才会是上面发的那种

了解了，这种应该属于QQ 自己的特殊格式，谢谢分享。(๑•̀ㅂ•́)و✧

类似这种特殊逻辑，暂时没有考虑放到主逻辑中去。image，text，html 这几种应该是比较纯粹的功能，特殊逻辑的解析，可能还是得实际业务中自己去处理比较好。毕竟不可能兼顾的全的，之前飞书也出现过类似的情况。

我把这个 issues Pin 住了，方便有其他类似情况的人找
