### ISSUE TITLE
Does the get_image Method Support Windows?

### ISSUE THREAD

**Issue by whwanyt** [ChurchTao/clipboard-rs#8]
Hello,

I'm experiencing an issue with the clipboard_rs crate on Windows 10, where I'm unable to retrieve an image from the clipboard using the provided example code. Despite having used the clipboard image tool to copy an image to the clipboard, the result returned by `get_image` is an empty image.

Here is the code snippet I'm using:

```rust
use clipboard_rs::{common::RustImage, Clipboard, ClipboardContext};
let ctx = ClipboardContext::new().unwrap();
let img = ctx.get_image().unwrap();
```

**Comment by ChurchTao** [comment]
@whwanyt 
Sorry, what I am testing here is the screenshot scene. What is your scene? Copy image files directly?

**Comment by ChurchTao** [comment]
Maybe I am not compatible with all image formats, you can provide 
- Before get_image(), print available_formats()
- How do you copy the picture?

**Comment by whwanyt** [comment]
@ChurchTao  I will reply to the code result at night because I am not in front of the computer right now.

**Comment by ChurchTao** [comment]
@whwanyt 
OK, I'm waiting for your news.

**Comment by ChurchTao** [comment]
I may have guessed your problem. If you use the `image.rs` demo to run, you need to change the file `saving path` to the path in your `own` operating system.

**Comment by whwanyt** [comment]
```rsut
use base64::{engine::general_purpose, Engine as _};
use clipboard_rs::{common::RustImage, Clipboard, ClipboardContext};
fn main() {
    let ctx = ClipboardContext::new().unwrap();
    let image = ctx.get_image().unwrap();
    match image.to_png() {
        Ok(res) => {
            let image_bytes = res.get_bytes();
            let base64_str = general_purpose::STANDARD_NO_PAD.encode(&image_bytes);
            println!("{}", base64_str);
        }
        Err(e) => {
            println!("err: {}", e)
        }
    }
}

```

**Comment by whwanyt** [comment]
I used the following sample code to get the clipboard picture and convert it to a base64 character string:
```rust
use base64::{engine::general_purpose, Engine as _};
use clipboard_rs::{common::RustImage, Clipboard, ClipboardContext};
fn main() {
    let ctx = ClipboardContext::new().unwrap();
    let image = ctx.get_image().unwrap();
    match image.to_png() {
        Ok(res) => {
            let image_bytes = res.get_bytes();
            let base64_str = general_purpose::STANDARD_NO_PAD.encode(&image_bytes);
            println!("{}", base64_str);
        }
        Err(e) => {
            println!("err: {}", e)
        }
    }
}
```
The output is as follows:
```
err: image is empty
```
I use [electron _ screenshot](https://github.com/liangtongzhuo/electron_screenshot) this plugin to achieve screenshots to the clipboard

**Comment by whwanyt** [comment]
> I may have guessed your problem. If you use the `image.rs` demo to run, you need to change the file `saving path` to the path in your `own` operating system. Like
> 
> ```rust
> const TMP_PATH: &str = "C:\\Windows\\Temp\\test.png";
> ```
> 
> I optimized the demo code so that it can run directly in Windows. You can take a look.
> 
> [8058263#diff-7bf759a09f1216d26074fca12a9e8a2aac8ca2d0392e34ed84fa6974d988aa9bR3](https://github.com/ChurchTao/clipboard-rs/commit/8058263c7bbb357ae14d1472838dfc46f94fd79a#diff-7bf759a09f1216d26074fca12a9e8a2aac8ca2d0392e34ed84fa6974d988aa9bR3)

Thank you for your reply, my goal is to get the image of the screen captured using the plugin by get_image method and convert it to base64 format

**Comment by ChurchTao** [comment]
@whwanyt 
Before calling get_image, print available_formats to show me.

**Comment by whwanyt** [comment]
> @whwanyt Before calling get_image, print available_formats to show me.

```
use clipboard_rs::{Clipboard, ClipboardContext};
fn main() {
    let ctx = ClipboardContext::new().unwrap();
    let types = ctx.available_formats().unwrap();
    println!("{:?}", types);
}
```
The print type results are as follows
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target\debug\imgdemo.exe`
["CF_BITMAP", "CF_DIB", "CF_DIBV5"]

```

**Comment by ChurchTao** [comment]
@whwanyt 
I understand. Sure enough, I am not compatible with images in bitmap format. I will fix it in the next version.

**Comment by ChurchTao** [comment]
Good news, I have solved the compatibility problem. Can you please try the code of this new branch again?

**Comment by ChurchTao** [comment]
The new version has been released. I will close this issue for now. If there are any problems, just reopen it.
